In [1]:
import numpy as np

In [5]:
inputs1 = [
    [1.0,2.0,3.0,2.5],
    [2.0,5.0,-1.0,2.0],
    [-1.5, 2.7, 3.3, -0.8]
]

weights1 = [
    [0.2, 0.8, -0.5, 1.0],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
]
biases1 = [2.0, 3.0, 0.5]

inputs2 = [
    [9, 8, 7,25, 6.3],
    [5.4, 4.5, 3.2, 2.1],
    [1.2, 2.3, 3.4, 4.5]
]

weights2 = [
    [0.35, 0.21, 0.54],
    [0.12, 0.34, 0.56],
    [0.36, 0.17, 0.81]
]

biases2 = [6, 4, 0.653]
outputs1 = np.dot(inputs1, np.array(weights1).T) + biases1
print(outputs1)
outputs2 = np.dot(outputs1,np.array(weights2).T) + biases2

print(outputs2)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
[[9.222   6.323   4.51855]
 [8.8429  4.5646  3.7113 ]
 [6.72825 4.5411  1.36033]]
